version: "1"
services:
  app:
    container_name: server
    restart: always
    build: ./todo-api
    ports:
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
